name: SE-IEA ESR - Metric Development/Idea Issue
description: Use this issue template if you have a lead on potential metric to include in the ESR
title: "[Metric Idea]: "
labels: ["Idea"]

body:
  - type: input
    id: metric_name
    attributes:
        label: Potential Metric Name
        description: What is the name of this potential indicator to include in the ESR?
        placeholder: "Ex: Sea Surface Temperature"
    validations:
        required: true
        
# Metric Description
  - type: textarea
    id: metric_description
    attributes:
        label: Metric description
        description: Plain language description (one sentence).
    validations:
        required: true
        
# Metric Data Source
  - type: textarea
    id: metric_data_source
    attributes:
        label: Data Source
        description: What is source of the data (e.g., the program name).
        
# Metric Data Source Link
  - type: input
    id: metric_data_link
    attributes:
        label: Data Source Link
        description: Input hyperlink to the data (if available).
        
# Metric References
  - type: textarea
    id: reference
    attributes:
        label: References
        description: Add any references such as peer reviewed or gray literature here.
        
#Your Name
  - type: input
    id: contributor_name
    attributes:
        label: IEA POC
        placeholder: Jane Doe
        
#Your email
  - type: input
    id: contributor_email
    attributes:
        label: IEA POC email
        placeholder: Jane.Doe@noaa.gov
        
#SME Name
  - type: input
    id: sme_name
    attributes:
        label: External SME name
        placeholder: John Doe
        
#SME email
  - type: input
    id: sme_email
    attributes:
        label: External SME email
        placeholder: John.Doe@miami.edu

#Data Steward Name
  - type: input
    id: data_steward_name
    attributes:
        label: Data Steward name
        placeholder: Bob Dole
        
#Data Steward email
  - type: input
    id: data_steward_email
    attributes:
        label: Data Steward email
        placeholder: Bob.Dole@miami.edu
        
# Contributors
  - type: textarea
    id: contributors
    attributes:
        label: Other Contributors
        description: Add any other collabotor names (internal or external).
        
        
