---
name: Metric Production Form
description: This form is to be filled out once all details about an ESR Metric have been
  compiled. Responses will directly populate the ESR Methods Document. 
title: "[PRODUCTION]:"
labels: '[PRODUCTION]'
assignees:

body:
  - type: markdown
    attributes:
      value: |
        Please do not fill out this form until ALL details have been compiled for your metric. These responses will directly populate the ESR Methods Document. Please contact Brendan, Brittany, Carissa, Mandy, or Will with questions.
        
  - type: input
    id: metric
    attributes:
      label: Metric Title (Full Name)
      description: The full, spelled out name of this metric.
      placeholder: Ex. Sea Surface Temperature (rather than SST)
    validations:
      required: true
        
  - type: input
    id: root
    attributes:
      label: Metric File Root Name
      description: For all files related to this metric, what will the shortened prefix be?
      placeholder: ex. degree_heating_wks for Degree Heating Weeks
    validations:
      required: true
      
  - type: input
    id: shortname
    attributes:
      label: Short Code Name
      description: What is the abbreviation or short name for this metric?
      placeholder: ex. SST for Sea Surface Temperature
    validations:
      required: false
      
  - type: dropdown
    id: parent_indicator
    attributes:
      label: Parent Indicator
      description: What Indicator will this metric contribute to?
      multiple: false
      options:
        - Test1
        - Test2
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Indicator Category
      description: To what Category do this metric and indicator belong?
      multiple: false
      options:
        - Test3
        - Test4
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Plain Language Description
      description: Please describe this metric using plain language in one sentence or less.
      value: "Satellite-derived monthly sea surface temperature for the Gulf of America EEZ."
    validations:
      required: true
